name: CI
on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Golang
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
      - name: Update Vendor
        run: go mod vendor -v
      - name: Build Operator
        run: ./hack/build/operator/build
      - name: Build Backup Operator
        run: ./hack/build/backup-operator/build
      - name: Build Restore Operator
        run: ./hack/build/restore-operator/build
      - name: Deploy
        run: ./hack/deploy.sh
        if: startsWith(github.ref, 'refs/tags')
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}